spring:
  data:
    mongodb:
      database: BookStoreUI
  mvc:
    static-path-pattern=/static/**:
mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean"
  change-logs-scan-package:
    - spring.homework.config