spring:
  batch:
    job:
      enabled: true
  data:
    mongodb:
      port: 0
      database: BookStoreUI
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    driver-class-name: org.h2.Driver
    username: sa
    password:
    data: classpath:/data.sql
    schema: classpath:/schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - spring.homework.changelogs